### ISSUE TITLE
Font size of code, in headings, and border box.

### ISSUE THREAD

**Issue by WorldSEnder** [Cveinnt/LetsMarkdown.com#1]
See https://letsmarkdown.com/spurious-kick-1370

The code tags should follow the font-height for the heading element they are contained in, but they are all exactly `font-height: 12px;`. I think changing this to a relative value, like `font-height: 0.9em;` could be sufficient to solve this issue in https://github.com/Cveinnt/LetsMarkdown.com/blob/d53114d36ac265989301c12a52f8a5e72dc25e30/src/components/markdown.css#L109

Moreover, if you browse [ \<insert random MDN docs\> ](https://developer.mozilla.org/en-US/docs/Web/CSS/font) as reference, you will see that they are using a font that has an Ascender (space above Capsize, i.e. font height) that balances out with the Descender (space below baseline, i.e. below font).[^1] This leads to the box around the text being more "center" than currently, where there appears to be less space above the font than below it. I'm sure you could find a suitable font for this.

Screenshot of the wrong font-height and missing Ascender, on current Firefox

![screenshot](https://user-images.githubusercontent.com/6527051/168450144-1ced05c9-c519-4bd0-8453-086fa57658bd.png)

[^1]: Terminology from https://seek-oss.github.io/capsize/

**Comment by Cveinnt** [comment]
Hi @WorldSEnder, thank you for submitting this issue! 

For the first problem, you can simply delete `font-size: 12px;` in `markdown.css`. I will be pushing a new update that fixes this as well. 

I used `Consolas, "Liberation Mono", Courier, monospace` as the default `font-family` for code blocks, and it looks like you don't have them installed and your browser is falling back to `Menlo` font, resulting in missing Ascender. Can you check if you have one of these installed and share which operating system you are on?

**Comment by WorldSEnder** [comment]
It seems my system installed Liberation Mono font is at fault, I'm running on arch linux. So there's not much you can do about that, except ship a correct font yourself. The font size is the more important part of the issue, anyway.
