### ISSUE TITLE
Implement XSS prevention measures

### ISSUE THREAD

**Issue by stypr** [Cveinnt/LetsMarkdown.com#10]
Please consider adding XSS countermeasures for this product. It's possible to run an arbitrary JavaScript code.

### To reproduce

1. go to https://letsmarkdown.com/
2. Get the generated URL ( https://letsmarkdown.com/pink-things-6832 )
3. Add the following details
```html
<img src=1 onerror="console.log(top.document.body.innerHTML='Unexpected_Page')">
```
4. Ask people to access `https://letsmarkdown.com/pink-things-6832`

### Suggested Fix

Consider disabling HTML feature on src/components/Score.tsx, or use the sanitizer package while HTML is turned on.

https://github.com/Cveinnt/LetsMarkdown.com/blob/d88c75b132e60733a5bc3eae43cf72d82eaafa4d/src/components/Score.tsx#L30

I assume HTML tags are not required for the most of the time.

Reference: https://github.com/markdown-it/markdown-it/blob/master/docs/security.md

**Comment by Cveinnt** [comment]
Hi @stypr , thanks for pointing this out - really appreciate the effort! 
I just pushed an update that fixes this with [markdown-it-sanitizer](https://www.npmjs.com/package/markdown-it-sanitizer). Let me know if you have any other suggestions security-wise!
