### ISSUE TITLE
Multi-arch does not seem to be supported

### ISSUE THREAD

**Issue by agneevX** [Cveinnt/LetsMarkdown.com#2]
Hello!

The README mentions that the Docker image supports multi-arch, but that does not appear to be the case here?

https://hub.docker.com/r/cveinnt/letsmarkdown/tags

**Comment by Cveinnt** [comment]
Hey @agneevX , thanks for pointing this out! I'm pushing an arm64 image now.

**Comment by uGeek** [comment]
I have the same problem.

Very good project.

Thank you

**Comment by Cveinnt** [comment]
Hi @uGeek, arm64 should be available now: https://hub.docker.com/r/cveinnt/letsmarkdown/tags

**Comment by agneevX** [comment]
Thanks @Cveinnt!
