### ISSUE TITLE
Websockets support needs to be enabled if hosted behind a reverse proxy

### ISSUE THREAD

**Issue by MarseyLivesMatter** [Cveinnt/LetsMarkdown.com#7]
Hello,

Thanks for making this, it's very useful! I was hosting the editor behind a Nginx reverse proxy using the Nginx Proxy Manager which I believe is pretty common amongst self-hosting enthusiasts and found out that the "Websockets Support" option was required to be enabled if not you would not be able to connect to the server to save your notes for collaboration. Just mentioning it here in case someone else faces the same problem.

**Comment by Cveinnt** [comment]
Hi, thanks for noticing this! Closing this issue for now.
