### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by humble-barnacle001** [Cveinnt/LetsMarkdown.com#9]
Add options for:
- export as html
- export as PDF
- export as md

**Comment by Cveinnt** [comment]
Hi, thanks for the suggestions - I'll consider adding these features in the next update.

**Comment by jonassmedegaard** [comment]
If this suggested feature has been implemented, then I recommend to brag about it in `READE.md`.
If not, then I recommend to keep this issue open, and perhaps flag it as a feature (i.e. a "nice to have", to distinguish from bugs).
